"""Render historical CFR or canonical VFR Stage 4 event overlays."""

from __future__ import annotations

import argparse
import json
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import cv2
import numpy as np

from src.project.clip_manifest import ClipManifest
from src.video.canonical_frames import CanonicalFrame, iter_canonical_frames
from src.video.frame_timestamps import FrameTimestampSidecar, validate_sidecar_against_manifest
from src.video.vfr_overlay import render_canonical_vfr_overlay


PROJECT_ROOT = Path(__file__).resolve().parents[2]
EVENT_COLORS = {
    "serve": (60, 220, 60),
    "hit": (0, 210, 255),
    "bounce": (255, 130, 40),
    "unknown": (180, 180, 180),
}


def load_event_rows(path: Path) -> list[dict[str, Any]]:
    """Read the normalized rows generated by event_loader."""
    if not path.exists():
        raise FileNotFoundError(f"Normalized events not found: {path}")
    payload = json.loads(path.read_text(encoding="utf-8"))
    events = payload.get("events") if isinstance(payload, dict) else None
    if not isinstance(events, list) or not events:
        raise ValueError(f"No normalized events found in {path}")
    return events


def _event_phase(event: dict[str, Any], frame_id: int) -> str:
    start = int(event["frame_start"])
    end = int(event["frame_end"])
    if start == end:
        return "POINT EVENT"
    if frame_id == start:
        return "START"
    if frame_id == end:
        return "END"
    return "ACTIVE"


def draw_events_frame(
    frame_bgr: np.ndarray,
    *,
    frame_id: int,
    timestamp_seconds: float,
    events: Sequence[dict[str, Any]],
) -> np.ndarray:
    """Draw frame identity, rally state, totals, and complete active-event evidence."""
    frame = frame_bgr.copy()
    height, width = frame.shape[:2]
    active = [
        event
        for event in events
        if int(event["frame_start"]) <= frame_id <= int(event["frame_end"])
    ]
    first_frame = min(int(event["frame_start"]) for event in events)
    last_frame = max(int(event["frame_end"]) for event in events)
    if frame_id < first_frame:
        rally_state = "BEFORE FIRST EVENT"
    elif frame_id > last_frame:
        rally_state = "AFTER LAST EVENT"
    else:
        rally_state = "RALLY ACTIVE"

    cv2.rectangle(frame, (0, 0), (width, 106), (0, 0, 0), -1)
    cv2.putText(
        frame,
        f"FRAME {frame_id:03d} / timestamp VFR {timestamp_seconds:.6f} s",
        (24, 40),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.82,
        (255, 255, 255),
        2,
        cv2.LINE_AA,
    )
    cv2.putText(
        frame,
        f"RALLY: {rally_state}  |  EVENTS REGISTERED: {len(events)}",
        (24, 82),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.72,
        (220, 220, 220),
        2,
        cv2.LINE_AA,
    )

    for row_index, event in enumerate(active):
        event_type = str(event["type"])
        color = EVENT_COLORS.get(event_type, EVENT_COLORS["unknown"])
        phase = _event_phase(event, frame_id)
        label = (
            f"{phase}  {event['id']} | {event_type} | player={event['player']} "
            f"| side={event['side']} | frames {event['frame_start']}-{event['frame_end']} "
            f"| time {float(event['time_start_seconds']):.6f}-"
            f"{float(event['time_end_seconds']):.6f} s"
        )
        top = 126 + row_index * 62
        cv2.rectangle(frame, (18, top), (width - 18, top + 48), (0, 0, 0), -1)
        cv2.rectangle(frame, (18, top), (width - 18, top + 48), color, 3)
        cv2.putText(
            frame,
            label,
            (32, top + 33),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.65,
            color,
            2,
            cv2.LINE_AA,
        )
    return frame


def _render_legacy_cfr_overlay(
    video_path: Path,
    events: Sequence[dict[str, Any]],
    output_path: Path,
) -> dict[str, float | int | str]:
    """Keep the historical Madrid OpenCV CFR path for backward compatibility."""
    capture = cv2.VideoCapture(str(video_path))
    if not capture.isOpened():
        raise RuntimeError(f"Could not open video: {video_path}")
    width = int(capture.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = capture.get(cv2.CAP_PROP_FPS) or 60.0
    output_path.parent.mkdir(parents=True, exist_ok=True)
    writer = cv2.VideoWriter(
        str(output_path),
        cv2.VideoWriter_fourcc(*"mp4v"),
        fps,
        (width, height),
    )
    if not writer.isOpened():
        capture.release()
        raise RuntimeError(f"Could not open output writer: {output_path}")

    frame_id = 0
    while True:
        ok, frame = capture.read()
        if not ok:
            break
        writer.write(
            draw_events_frame(
                frame,
                frame_id=frame_id,
                timestamp_seconds=frame_id / fps,
                events=events,
            )
        )
        frame_id += 1
    capture.release()
    writer.release()

    check = cv2.VideoCapture(str(output_path))
    readable, _ = check.read()
    check.release()
    if not readable:
        raise RuntimeError(f"Overlay was written but cannot be read: {output_path}")
    return {
        "mode": "legacy_cfr",
        "frames": frame_id,
        "width": width,
        "height": height,
        "duration_seconds": frame_id / fps,
    }


def render_events_overlay(
    video_path: Path,
    events_path: Path,
    output_path: Path,
    *,
    manifest: ClipManifest | None = None,
    timestamps: Sequence[float] | None = None,
) -> dict[str, float | int | str]:
    """Render a legacy CFR overlay or an orientation-safe timestamp-driven VFR one."""
    if not video_path.exists():
        raise FileNotFoundError(f"Reference video not found: {video_path}")
    events = load_event_rows(events_path)
    if manifest is None:
        return _render_legacy_cfr_overlay(video_path, events, output_path)
    if timestamps is None:
        raise ValueError("Canonical VFR rendering requires explicit timestamps")
    if len(timestamps) != manifest.frames_total:
        raise ValueError("Timestamp count does not match manifest frames_total")
    for event in events:
        if not 0 <= int(event["frame_start"]) <= int(event["frame_end"]) < manifest.frames_total:
            raise ValueError(f"Event {event['id']} is outside the manifest frame range")

    def render(record: CanonicalFrame) -> np.ndarray:
        return draw_events_frame(
            record.image_bgr,
            frame_id=record.frame_id,
            timestamp_seconds=record.timestamp_seconds,
            events=events,
        )

    metadata = render_canonical_vfr_overlay(
        iter_canonical_frames(video_path, manifest, timestamps=timestamps),
        output_path,
        render,
        expected_frames=manifest.frames_total,
        expected_width=manifest.canonical_width,
        expected_height=manifest.canonical_height,
    )
    return {"mode": "canonical_vfr", **metadata}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--video",
        type=Path,
        default=PROJECT_ROOT / "data" / "reference_clip" / "madrid_R1.mov",
    )
    parser.add_argument(
        "--events",
        type=Path,
        default=PROJECT_ROOT / "outputs" / "stage_4" / "events.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=PROJECT_ROOT / "outputs" / "stage_4" / "events_overlay.mp4",
    )
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--frame-timestamps", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if (args.manifest is None) != (args.frame_timestamps is None):
        raise SystemExit("ERROR: --manifest and --frame-timestamps must be supplied together")
    manifest = ClipManifest.read(args.manifest) if args.manifest else None
    timestamps = None
    if args.frame_timestamps:
        sidecar = FrameTimestampSidecar.read(args.frame_timestamps)
        if manifest is None:
            raise SystemExit("ERROR: manifest is required for VFR rendering")
        validate_sidecar_against_manifest(sidecar, manifest)
        timestamps = [frame.timestamp_seconds for frame in sidecar.frames]
    metadata = render_events_overlay(
        args.video,
        args.events,
        args.output,
        manifest=manifest,
        timestamps=timestamps,
    )
    print(f"Event overlay written to {args.output}: {metadata}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
