"""Render normalized Stage 4 events over the reference video."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import cv2


PROJECT_ROOT = Path(__file__).resolve().parents[2]
EVENT_COLORS = {
    "serve": (60, 220, 60),
    "hit": (0, 210, 255),
    "bounce": (255, 130, 40),
    "unknown": (180, 180, 180),
}


def load_event_rows(path: Path) -> list[dict[str, Any]]:
    """Read the normalized rows generated by event_loader."""
    if not path.exists():
        raise FileNotFoundError(f"Normalized events not found: {path}")
    payload = json.loads(path.read_text(encoding="utf-8"))
    events = payload.get("events") if isinstance(payload, dict) else None
    if not isinstance(events, list) or not events:
        raise ValueError(f"No normalized events found in {path}")
    return events


def render_events_overlay(video_path: Path, events_path: Path, output_path: Path) -> None:
    """Render event ranges without changing their timing or classification."""
    if not video_path.exists():
        raise FileNotFoundError(f"Reference video not found: {video_path}")
    events = load_event_rows(events_path)
    capture = cv2.VideoCapture(str(video_path))
    if not capture.isOpened():
        raise RuntimeError(f"Could not open video: {video_path}")

    width = int(capture.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = capture.get(cv2.CAP_PROP_FPS) or 60.0
    output_path.parent.mkdir(parents=True, exist_ok=True)
    writer = cv2.VideoWriter(
        str(output_path),
        cv2.VideoWriter_fourcc(*"mp4v"),
        fps,
        (width, height),
    )
    if not writer.isOpened():
        capture.release()
        raise RuntimeError(f"Could not open output writer: {output_path}")

    frame_id = 0
    while True:
        ok, frame = capture.read()
        if not ok:
            break

        active = [
            event
            for event in events
            if int(event["frame_start"]) <= frame_id <= int(event["frame_end"])
        ]
        cv2.putText(
            frame,
            f"frame {frame_id} | {frame_id / fps:.3f}s",
            (24, 38),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.75,
            (255, 255, 255),
            2,
            cv2.LINE_AA,
        )
        for row_index, event in enumerate(active):
            event_type = str(event["type"])
            color = EVENT_COLORS.get(event_type, EVENT_COLORS["unknown"])
            label = (
                f"{event['id']} | {event_type} | {event['player']} | "
                f"{event['shot_type']} | {event['court_zone']}"
            )
            y = 78 + row_index * 38
            cv2.rectangle(frame, (18, y - 27), (width - 18, y + 8), (0, 0, 0), -1)
            cv2.putText(
                frame,
                label,
                (28, y),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.68,
                color,
                2,
                cv2.LINE_AA,
            )

        writer.write(frame)
        frame_id += 1

    capture.release()
    writer.release()

    check = cv2.VideoCapture(str(output_path))
    readable, _ = check.read()
    check.release()
    if not readable:
        raise RuntimeError(f"Overlay was written but cannot be read: {output_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--video",
        type=Path,
        default=PROJECT_ROOT / "data" / "reference_clip" / "madrid_R1.mov",
    )
    parser.add_argument(
        "--events",
        type=Path,
        default=PROJECT_ROOT / "outputs" / "stage_4" / "events.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=PROJECT_ROOT / "outputs" / "stage_4" / "events_overlay.mp4",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    render_events_overlay(args.video, args.events, args.output)
    print(f"Event overlay written to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
